name: Python CI Pytest And Ruff

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Python 3.12
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # Install Poetry
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -

      # Install dependencies with Poetry
      - name: Install dependencies
        run: |
          poetry install
      
      # Run Ruff
      - name: Run Ruff
        run: |
          poetry run ruff check personaledge tests

      # Run pytest
      - name: Run pytest
        run: |
          poetry run pytest
